// Generated by gencpp from file yocs_msgs/NavgationCtrlServiceRequest.msg
// DO NOT EDIT!


#ifndef YOCS_MSGS_MESSAGE_NAVGATIONCTRLSERVICEREQUEST_H
#define YOCS_MSGS_MESSAGE_NAVGATIONCTRLSERVICEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <yocs_msgs/NavigationControl.h>

namespace yocs_msgs
{
template <class ContainerAllocator>
struct NavgationCtrlServiceRequest_
{
  typedef NavgationCtrlServiceRequest_<ContainerAllocator> Type;

  NavgationCtrlServiceRequest_()
    : msg()  {
    }
  NavgationCtrlServiceRequest_(const ContainerAllocator& _alloc)
    : msg(_alloc)  {
  (void)_alloc;
    }



   typedef  ::yocs_msgs::NavigationControl_<ContainerAllocator>  _msg_type;
  _msg_type msg;




  typedef boost::shared_ptr< ::yocs_msgs::NavgationCtrlServiceRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yocs_msgs::NavgationCtrlServiceRequest_<ContainerAllocator> const> ConstPtr;

}; // struct NavgationCtrlServiceRequest_

typedef ::yocs_msgs::NavgationCtrlServiceRequest_<std::allocator<void> > NavgationCtrlServiceRequest;

typedef boost::shared_ptr< ::yocs_msgs::NavgationCtrlServiceRequest > NavgationCtrlServiceRequestPtr;
typedef boost::shared_ptr< ::yocs_msgs::NavgationCtrlServiceRequest const> NavgationCtrlServiceRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yocs_msgs::NavgationCtrlServiceRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yocs_msgs::NavgationCtrlServiceRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yocs_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'yocs_msgs': ['/home/ouiyeah/catkin_ws/src/yocs_msgs/msg', '/home/ouiyeah/catkin_ws/devel/share/yocs_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::yocs_msgs::NavgationCtrlServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yocs_msgs::NavgationCtrlServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yocs_msgs::NavgationCtrlServiceRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yocs_msgs::NavgationCtrlServiceRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yocs_msgs::NavgationCtrlServiceRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yocs_msgs::NavgationCtrlServiceRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yocs_msgs::NavgationCtrlServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6565f8eb58c4fa39018bda5c0d94f007";
  }

  static const char* value(const ::yocs_msgs::NavgationCtrlServiceRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6565f8eb58c4fa39ULL;
  static const uint64_t static_value2 = 0x018bda5c0d94f007ULL;
};

template<class ContainerAllocator>
struct DataType< ::yocs_msgs::NavgationCtrlServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yocs_msgs/NavgationCtrlServiceRequest";
  }

  static const char* value(const ::yocs_msgs::NavgationCtrlServiceRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yocs_msgs::NavgationCtrlServiceRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "NavigationControl msg\n\
\n\
================================================================================\n\
MSG: yocs_msgs/NavigationControl\n\
# control the way point/trajectory navigation\n\
int8 control\n\
\n\
int8 STOP  = 0\n\
int8 START = 1\n\
int8 PAUSE = 2\n\
\n\
# name of the way point(s) / trajectory to be execute\n\
# leave empty, when stopping or pausing\n\
string goal_name\n\
";
  }

  static const char* value(const ::yocs_msgs::NavgationCtrlServiceRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yocs_msgs::NavgationCtrlServiceRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.msg);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct NavgationCtrlServiceRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yocs_msgs::NavgationCtrlServiceRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yocs_msgs::NavgationCtrlServiceRequest_<ContainerAllocator>& v)
  {
    s << indent << "msg: ";
    s << std::endl;
    Printer< ::yocs_msgs::NavigationControl_<ContainerAllocator> >::stream(s, indent + "  ", v.msg);
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOCS_MSGS_MESSAGE_NAVGATIONCTRLSERVICEREQUEST_H
