// Generated by gencpp from file yocs_msgs/VirtualObstacles.msg
// DO NOT EDIT!


#ifndef YOCS_MSGS_MESSAGE_VIRTUALOBSTACLES_H
#define YOCS_MSGS_MESSAGE_VIRTUALOBSTACLES_H

#include <ros/service_traits.h>


#include <yocs_msgs/VirtualObstaclesRequest.h>
#include <yocs_msgs/VirtualObstaclesResponse.h>


namespace yocs_msgs
{

struct VirtualObstacles
{

typedef VirtualObstaclesRequest Request;
typedef VirtualObstaclesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct VirtualObstacles
} // namespace yocs_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::yocs_msgs::VirtualObstacles > {
  static const char* value()
  {
    return "5f239ab4c346711409318bb572e09921";
  }

  static const char* value(const ::yocs_msgs::VirtualObstacles&) { return value(); }
};

template<>
struct DataType< ::yocs_msgs::VirtualObstacles > {
  static const char* value()
  {
    return "yocs_msgs/VirtualObstacles";
  }

  static const char* value(const ::yocs_msgs::VirtualObstacles&) { return value(); }
};


// service_traits::MD5Sum< ::yocs_msgs::VirtualObstaclesRequest> should match 
// service_traits::MD5Sum< ::yocs_msgs::VirtualObstacles > 
template<>
struct MD5Sum< ::yocs_msgs::VirtualObstaclesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::yocs_msgs::VirtualObstacles >::value();
  }
  static const char* value(const ::yocs_msgs::VirtualObstaclesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::yocs_msgs::VirtualObstaclesRequest> should match 
// service_traits::DataType< ::yocs_msgs::VirtualObstacles > 
template<>
struct DataType< ::yocs_msgs::VirtualObstaclesRequest>
{
  static const char* value()
  {
    return DataType< ::yocs_msgs::VirtualObstacles >::value();
  }
  static const char* value(const ::yocs_msgs::VirtualObstaclesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::yocs_msgs::VirtualObstaclesResponse> should match 
// service_traits::MD5Sum< ::yocs_msgs::VirtualObstacles > 
template<>
struct MD5Sum< ::yocs_msgs::VirtualObstaclesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::yocs_msgs::VirtualObstacles >::value();
  }
  static const char* value(const ::yocs_msgs::VirtualObstaclesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::yocs_msgs::VirtualObstaclesResponse> should match 
// service_traits::DataType< ::yocs_msgs::VirtualObstacles > 
template<>
struct DataType< ::yocs_msgs::VirtualObstaclesResponse>
{
  static const char* value()
  {
    return DataType< ::yocs_msgs::VirtualObstacles >::value();
  }
  static const char* value(const ::yocs_msgs::VirtualObstaclesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // YOCS_MSGS_MESSAGE_VIRTUALOBSTACLES_H
