// Generated by gencpp from file yocs_msgs/VirtualObstaclesRequest.msg
// DO NOT EDIT!


#ifndef YOCS_MSGS_MESSAGE_VIRTUALOBSTACLESREQUEST_H
#define YOCS_MSGS_MESSAGE_VIRTUALOBSTACLESREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Polygon.h>

namespace yocs_msgs
{
template <class ContainerAllocator>
struct VirtualObstaclesRequest_
{
  typedef VirtualObstaclesRequest_<ContainerAllocator> Type;

  VirtualObstaclesRequest_()
    : obstacles()  {
    }
  VirtualObstaclesRequest_(const ContainerAllocator& _alloc)
    : obstacles(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Polygon_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Polygon_<ContainerAllocator> >::other >  _obstacles_type;
  _obstacles_type obstacles;




  typedef boost::shared_ptr< ::yocs_msgs::VirtualObstaclesRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::yocs_msgs::VirtualObstaclesRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VirtualObstaclesRequest_

typedef ::yocs_msgs::VirtualObstaclesRequest_<std::allocator<void> > VirtualObstaclesRequest;

typedef boost::shared_ptr< ::yocs_msgs::VirtualObstaclesRequest > VirtualObstaclesRequestPtr;
typedef boost::shared_ptr< ::yocs_msgs::VirtualObstaclesRequest const> VirtualObstaclesRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::yocs_msgs::VirtualObstaclesRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::yocs_msgs::VirtualObstaclesRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace yocs_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'yocs_msgs': ['/home/ouiyeah/catkin_ws/src/yocs_msgs/msg', '/home/ouiyeah/catkin_ws/devel/share/yocs_msgs/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::yocs_msgs::VirtualObstaclesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::yocs_msgs::VirtualObstaclesRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yocs_msgs::VirtualObstaclesRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::yocs_msgs::VirtualObstaclesRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yocs_msgs::VirtualObstaclesRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::yocs_msgs::VirtualObstaclesRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::yocs_msgs::VirtualObstaclesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9e2e12e8f589d0efa82c3de160648305";
  }

  static const char* value(const ::yocs_msgs::VirtualObstaclesRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9e2e12e8f589d0efULL;
  static const uint64_t static_value2 = 0xa82c3de160648305ULL;
};

template<class ContainerAllocator>
struct DataType< ::yocs_msgs::VirtualObstaclesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "yocs_msgs/VirtualObstaclesRequest";
  }

  static const char* value(const ::yocs_msgs::VirtualObstaclesRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::yocs_msgs::VirtualObstaclesRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
\n\
\n\
\n\
geometry_msgs/Polygon[] obstacles\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Polygon\n\
#A specification of a polygon where the first and last points are assumed to be connected\n\
Point32[] points\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
";
  }

  static const char* value(const ::yocs_msgs::VirtualObstaclesRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::yocs_msgs::VirtualObstaclesRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.obstacles);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VirtualObstaclesRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::yocs_msgs::VirtualObstaclesRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::yocs_msgs::VirtualObstaclesRequest_<ContainerAllocator>& v)
  {
    s << indent << "obstacles[]" << std::endl;
    for (size_t i = 0; i < v.obstacles.size(); ++i)
    {
      s << indent << "  obstacles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Polygon_<ContainerAllocator> >::stream(s, indent + "    ", v.obstacles[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // YOCS_MSGS_MESSAGE_VIRTUALOBSTACLESREQUEST_H
