(cl:defpackage scheduling_msgs-msg
  (:use )
  (:export
   "<AGVLIST>"
   "AGVLIST"
   "<TASKSTATUS>"
   "TASKSTATUS"
   "<NEWTASK2>"
   "NEWTASK2"
   "<PATH>"
   "PATH"
   "<AGVPOSE>"
   "AGVPOSE"
   "<NEWTASK>"
   "NEWTASK"
   "<SERVERSTATUS>"
   "SERVERSTATUS"
   "<AGV>"
   "AGV"
   "<ROADSET>"
   "ROADSET"
   "<PATHWITHID>"
   "PATHWITHID"
   "<TASKLIST2>"
   "TASKLIST2"
   "<PATHSTAMPWITHID>"
   "PATHSTAMPWITHID"
   "<TASKSTATUS2>"
   "TASKSTATUS2"
   "<TASK>"
   "TASK"
   "<TASKLIST>"
   "TASKLIST"
  ))

