// Generated by gencpp from file task_manager/TaskControlStatus.msg
// DO NOT EDIT!


#ifndef TASK_MANAGER_MESSAGE_TASKCONTROLSTATUS_H
#define TASK_MANAGER_MESSAGE_TASKCONTROLSTATUS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace task_manager
{
template <class ContainerAllocator>
struct TaskControlStatus_
{
  typedef TaskControlStatus_<ContainerAllocator> Type;

  TaskControlStatus_()
    : status(0)
    , status_desc()
    , task_name()  {
    }
  TaskControlStatus_(const ContainerAllocator& _alloc)
    : status(0)
    , status_desc(_alloc)
    , task_name(_alloc)  {
  (void)_alloc;
    }



   typedef int8_t _status_type;
  _status_type status;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _status_desc_type;
  _status_desc_type status_desc;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _task_name_type;
  _task_name_type task_name;


    enum { ERROR = -1 };
     enum { IDLING = 0 };
     enum { RUNNING = 1 };
     enum { PAUSED = 2 };
     enum { COMPLETED = 3 };
     enum { CANCELLED = 4 };
     enum { SUB_CANCELLED = 5 };
 

  typedef boost::shared_ptr< ::task_manager::TaskControlStatus_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::task_manager::TaskControlStatus_<ContainerAllocator> const> ConstPtr;

}; // struct TaskControlStatus_

typedef ::task_manager::TaskControlStatus_<std::allocator<void> > TaskControlStatus;

typedef boost::shared_ptr< ::task_manager::TaskControlStatus > TaskControlStatusPtr;
typedef boost::shared_ptr< ::task_manager::TaskControlStatus const> TaskControlStatusConstPtr;

// constants requiring out of line definition

   

   

   

   

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::task_manager::TaskControlStatus_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::task_manager::TaskControlStatus_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace task_manager

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'task_manager': ['/home/ouiyeah/catkin_ws/src/hitrobot/task_manager/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::task_manager::TaskControlStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::task_manager::TaskControlStatus_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task_manager::TaskControlStatus_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::task_manager::TaskControlStatus_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task_manager::TaskControlStatus_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::task_manager::TaskControlStatus_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::task_manager::TaskControlStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ab313481ad0d72bce6bc5e140447df06";
  }

  static const char* value(const ::task_manager::TaskControlStatus_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xab313481ad0d72bcULL;
  static const uint64_t static_value2 = 0xe6bc5e140447df06ULL;
};

template<class ContainerAllocator>
struct DataType< ::task_manager::TaskControlStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "task_manager/TaskControlStatus";
  }

  static const char* value(const ::task_manager::TaskControlStatus_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::task_manager::TaskControlStatus_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Control the task navigation\n\
int8 status\n\
\n\
int8 ERROR     = -1\n\
int8 IDLING    = 0\n\
int8 RUNNING   = 1\n\
int8 PAUSED    = 2\n\
int8 COMPLETED = 3\n\
int8 CANCELLED = 4\n\
int8 SUB_CANCELLED = 5\n\
\n\
# Human-readable status description\n\
string status_desc\n\
string task_name\n\
";
  }

  static const char* value(const ::task_manager::TaskControlStatus_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::task_manager::TaskControlStatus_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.status);
      stream.next(m.status_desc);
      stream.next(m.task_name);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskControlStatus_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::task_manager::TaskControlStatus_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::task_manager::TaskControlStatus_<ContainerAllocator>& v)
  {
    s << indent << "status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.status);
    s << indent << "status_desc: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.status_desc);
    s << indent << "task_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.task_name);
  }
};

} // namespace message_operations
} // namespace ros

#endif // TASK_MANAGER_MESSAGE_TASKCONTROLSTATUS_H
