(cl:defpackage cob_frame_tracker-msg
  (:use )
  (:export
   "<FRAMETRACKINGRESULT>"
   "FRAMETRACKINGRESULT"
   "<FRAMETRACKINGGOAL>"
   "FRAMETRACKINGGOAL"
   "<FRAMETRACKINGACTIONGOAL>"
   "FRAMETRACKINGACTIONGOAL"
   "<FRAMETRACKINGACTIONRESULT>"
   "FRAMETRACKINGACTIONRESULT"
   "<FRAMETRACKINGACTIONFEEDBACK>"
   "FRAMETRACKINGACTIONFEEDBACK"
   "<FRAMETRACKINGACTION>"
   "FRAMETRACKINGACTION"
   "<FRAMETRACKINGFEEDBACK>"
   "FRAMETRACKINGFEEDBACK"
  ))

