(cl:defpackage yocs_msgs-srv
  (:use )
  (:export
   "DBPARAMCONTROL"
   "<DBPARAMCONTROL-REQUEST>"
   "DBPARAMCONTROL-REQUEST"
   "<DBPARAMCONTROL-RESPONSE>"
   "DBPARAMCONTROL-RESPONSE"
   "WAYPOINTLISTSERVICE"
   "<WAYPOINTLISTSERVICE-REQUEST>"
   "WAYPOINTLISTSERVICE-REQUEST"
   "<WAYPOINTLISTSERVICE-RESPONSE>"
   "WAYPOINTLISTSERVICE-RESPONSE"
   "VIRTUALOBSTACLES"
   "<VIRTUALOBSTACLES-REQUEST>"
   "VIRTUALOBSTACLES-REQUEST"
   "<VIRTUALOBSTACLES-RESPONSE>"
   "VIRTUALOBSTACLES-RESPONSE"
   "NAVGATIONCTRLSERVICE"
   "<NAVGATIONCTRLSERVICE-REQUEST>"
   "NAVGATIONCTRLSERVICE-REQUEST"
   "<NAVGATIONCTRLSERVICE-RESPONSE>"
   "NAVGATIONCTRLSERVICE-RESPONSE"
  ))

