(cl:defpackage cob_cartesian_controller-msg
  (:use )
  (:export
   "<CARTESIANCONTROLLERACTIONFEEDBACK>"
   "CARTESIANCONTROLLERACTIONFEEDBACK"
   "<CARTESIANCONTROLLERRESULT>"
   "CARTESIANCONTROLLERRESULT"
   "<CARTESIANCONTROLLERACTIONRESULT>"
   "CARTESIANCONTROLLERACTIONRESULT"
   "<CARTESIANCONTROLLERACTIONGOAL>"
   "CARTESIANCONTROLLERACTIONGOAL"
   "<CARTESIANCONTROLLERFEEDBACK>"
   "CARTESIANCONTROLLERFEEDBACK"
   "<CARTESIANCONTROLLERGOAL>"
   "CARTESIANCONTROLLERGOAL"
   "<CARTESIANCONTROLLERACTION>"
   "CARTESIANCONTROLLERACTION"
   "<MOVELIN>"
   "MOVELIN"
   "<PROFILE>"
   "PROFILE"
   "<MOVECIRC>"
   "MOVECIRC"
  ))

