; Auto-generated. Do not edit!


(cl:in-package cob_cartesian_controller-msg)


;//! \htmlinclude CartesianControllerFeedback.msg.html

(cl:defclass <CartesianControllerFeedback> (roslisp-msg-protocol:ros-message)
  ((state
    :reader state
    :initarg :state
    :type cl:fixnum
    :initform 0)
   (message
    :reader message
    :initarg :message
    :type cl:string
    :initform ""))
)

(cl:defclass CartesianControllerFeedback (<CartesianControllerFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <CartesianControllerFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'CartesianControllerFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_cartesian_controller-msg:<CartesianControllerFeedback> is deprecated: use cob_cartesian_controller-msg:CartesianControllerFeedback instead.")))

(cl:ensure-generic-function 'state-val :lambda-list '(m))
(cl:defmethod state-val ((m <CartesianControllerFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_cartesian_controller-msg:state-val is deprecated.  Use cob_cartesian_controller-msg:state instead.")
  (state m))

(cl:ensure-generic-function 'message-val :lambda-list '(m))
(cl:defmethod message-val ((m <CartesianControllerFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_cartesian_controller-msg:message-val is deprecated.  Use cob_cartesian_controller-msg:message instead.")
  (message m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <CartesianControllerFeedback>) ostream)
  "Serializes a message object of type '<CartesianControllerFeedback>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'state)) ostream)
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'message))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'message))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <CartesianControllerFeedback>) istream)
  "Deserializes a message object of type '<CartesianControllerFeedback>"
    (cl:setf (cl:ldb (cl:byte 8 0) (cl:slot-value msg 'state)) (cl:read-byte istream))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'message) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'message) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<CartesianControllerFeedback>)))
  "Returns string type for a message object of type '<CartesianControllerFeedback>"
  "cob_cartesian_controller/CartesianControllerFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'CartesianControllerFeedback)))
  "Returns string type for a message object of type 'CartesianControllerFeedback"
  "cob_cartesian_controller/CartesianControllerFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<CartesianControllerFeedback>)))
  "Returns md5sum for a message object of type '<CartesianControllerFeedback>"
  "7ae2c26d6cd43624ca68107440b53b96")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'CartesianControllerFeedback)))
  "Returns md5sum for a message object of type 'CartesianControllerFeedback"
  "7ae2c26d6cd43624ca68107440b53b96")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<CartesianControllerFeedback>)))
  "Returns full string definition for message of type '<CartesianControllerFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%uint8 state~%string message~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'CartesianControllerFeedback)))
  "Returns full string definition for message of type 'CartesianControllerFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Define a feedback message~%uint8 state~%string message~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <CartesianControllerFeedback>))
  (cl:+ 0
     1
     4 (cl:length (cl:slot-value msg 'message))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <CartesianControllerFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'CartesianControllerFeedback
    (cl:cons ':state (state msg))
    (cl:cons ':message (message msg))
))
