var BaseEvent=BaseEvent||{REVISION:"0.0.5.0-2016-11.15"};
$(function(){document.oncontextmenu=function(a){a.preventDefault()};NavJobs.subscribeShellFeedback(ShellFeedbackCallBack);var a=new NavEvent.Msg(NavEvent.CmdEnum.Userauth);NavEvent.cmdTopic.publish(a);var b=!0;$("#hrg-navigation-main-page").live("pageshow",function(a,h){if("hrg-login-page"==h.prevPage[0].id){if(b){b=!1;var e="<a href='#hty-user-manger-page' data-transition='slide' class='btn-hty ui-btn ui-icon-hrg-user ui-btn-icon-notext ui-corner-all ui-btn-left'></a>";$("#hrg-menu-page-header").append(e);
$("#hrg-menu-page-content").append("<a href='#hty-super-page' class='btn-hty' data-transition='slide' data-role='button' data-icon='carat-r' data-iconpos='right' style='background: #b6ff00;'>HTY-SUPER SD6</a>");MapCurrentCmd=MapCmdEnum.map_select;e=new NavEvent.Msg(NavEvent.CmdEnum.Map_Select);NavEvent.cmdTopic.publish(e);NavJobs.LoadMap(800,800,"nav");$("#nav canvas").on("taphold",function(){$("#hrg-manual-control-popup").popup();$("#hrg-manual-control-popup").popup("open")})}}else"hrg-main-page"==
h.prevPage[0].id&&b&&(b=!1,e="<a href='#hrg-super-page' data-transition='slide' class='ui-btn ui-icon-hrg-user ui-btn-icon-notext ui-corner-all ui-btn-left'></a>",$("#hrg-menu-page-header").append(e),MapCurrentCmd=MapCmdEnum.map_select,e=new NavEvent.Msg(NavEvent.CmdEnum.Map_Select),NavEvent.cmdTopic.publish(e),NavJobs.LoadMap(800,800,"nav"),$("#nav canvas").on("taphold",function(){$("#hrg-manual-control-popup").popup();$("#hrg-manual-control-popup").popup("open")}))});$("#btn-lock-software").click(function(){NavEvent.data.LockScreen=
!0;$("#hrg-lock-software-popup").popup("open")});$("#btn-unlock-software").click(function(){$("#lock-password")[0].value==NavEvent.data.LoginPassword?($("#lock-password")[0].value="",$("#hrg-lock-software-popup").popup("close"),NavEvent.data.LockScreen=!1):sweetAlert("\u8f93\u5165\u5bc6\u7801\u9519\u8bef","","error")});$(".btn-start-create-map").click(function(){"\u6a21\u5f0f\u5207\u6362\u4e2d..."!=$(this).text()&&($(this).text("\u6a21\u5f0f\u5207\u6362\u4e2d..."),$(this).buttonMarkup({icon:"hrg-load"}),
NavEvent.data.NavigationMode==NavEvent.CmdEnum.Navigation?NavJobs.Gmapping():NavEvent.data.NavigationMode==NavEvent.CmdEnum.Gmapping?NavJobs.Navigation():NavEvent.data.NavigationMode!=NavEvent.CmdEnum.Coverting&&($(this).text("\u5f00\u542f\u5efa\u56fe"),$(this).buttonMarkup({icon:"hrg-stop"}),sweetAlert("\u83b7\u53d6\u5bfc\u822a\u72b6\u6001\u5931\u8d25","","error")))});$("#hrg-map-wizard-frist").live("pageshow",function(a,b){NavEvent.data.CreateMapFlag=!0;NavJobs.subscribeDiagnostics(DiagnosticsCallback)});
$("#hrg-map-wizard-frist").live("pagehide",function(a,b){});$("#hrg-map-wizard-frist-close").click(function(){$.mobile.changePage("#hrg-menu-page",{transition:"slide"})});$("#hrg-map-wizard-second").live("pageshow",function(a,b){NavJobs.LoadMap(800,800,"nav1");$("#nav1 canvas").on("taphold",function(){$("#hrg-manual-control-popup").popup();$("#hrg-manual-control-popup").popup("open")})});$("#map-save").click(function(){NavJobs.SaveMap();$(this).buttonMarkup({icon:"hrg-load"})});$("#hrg-map-wizard-second").live("pagehide",
function(a,b){NavJobs.RemoveMap("nav1");$("#nav1 canvas").off("taphold")});$("#hrg-map-wizard-third").live("pageshow",function(a,b){DisableBrush(d);$("#map-edit-canvas").hide();$("#map-edit-canvas-father img").show();NavJobs.subscribeMapEdit();$(this).css("background","white")});var d=document.getElementById("map-edit-canvas-father");$("#map-scorll").click(function(){"hidden"==d.style.overflow?DisableBrush(d):EnableBrush(d)});$("#map-edit-save").click(function(){$(this).buttonMarkup({icon:"hrg-load"});
NavJobs.SaveMapEdit()});$("#map-lines-delete").click(function(){BushEvent.bushdata.mapEditcolor="white";BushEvent.bushdata.mapEditlineWidth=5;$(this).buttonMarkup({icon:"hrg-edit-red"});$("#map-lines-add").buttonMarkup({icon:"hrg-edit-white"})});$("#map-lines-add").click(function(){BushEvent.bushdata.mapEditcolor="black";BushEvent.bushdata.mapEditlineWidth=3;$(this).buttonMarkup({icon:"hrg-edit-red"});$("#map-lines-delete").buttonMarkup({icon:"hrg-edit-white"})});$("#hrg-map-wizard-third").live("pagehide",
function(a,b){NavJobs.unsubscribeDiagnostics(DiagnosticsCallback);NavEvent.data.CreateMapFlag=!1});$("#hrg-system-diagnosis-page").live("pageshow",function(a,b){NavJobs.subscribeDiagnostics(DiagnosisPageCallBack)});$("#hrg-system-diagnosis-page").live("pagehide",function(a,b){$("#diagnostics-list div").remove();$("#hrg-diagnosis-content img").show()});NavEvent.poseTopic.subscribe(function(a){$("#pos_x").val(a.position.x);$("#pos_y").val(a.position.y);$("#ori_z").val(a.orientation.z);$("#ori_w").val(a.orientation.w)});
NavEvent.WaypointTopic.subscribe(function(a){console.log(a);NavEvent.data.WaypointList=a;$("#waypoint-list")[0].innerHTML="";NavEvent.data.WaypointsHtml="<option value='-1'>\u7a7a</option>";for(var b=0;b<a.waypoints.length;b++){var e=a.waypoints[b].name,c="location",c=getWaypointIcon(b),c=" <div class='ui-grid-a' id='way"+e+"'><div class='ui-block-a'><a style='padding:0.1em;margin-left:0;' data-icon='"+c+"' class='btn btn1' id='btn-waypoint-"+e+"' onclick='goPostion(this)'>"+e+"</a></div><div class='ui-block-b'><a style='padding:0.1em;margin-left:0;' data-icon='delete' class='btn btn1' onclick='WaypointDelete(this)'>\u5220\u9664</a></div></div>";
NavEvent.data.WaypointsHtml+="<option value='"+b+"'>"+e+"</option>";$("#waypoint-list").append(c)}$(".btn").button()});NavEvent.TrajectoryTopic.subscribe(function(a){console.log(a);NavEvent.data.TrajectoryList=a;$("#trajectory-list")[0].innerHTML="";for(var b=0;b<a.trajectories.length;b++){var e=a.trajectories[b].name,e="<div data-role='collapsible' class='coll'><h3>"+e+"</h3> <div class='ui-grid-b' id='tra"+e+"'><div class='ui-block-a'><a style='padding:0.1em;margin-left:0;' data-icon='location' class='btn btn1'id='btn-trajectorie-"+
e+"' onclick='goPostion(this)'>"+e+"</a></div><div class='ui-block-b'><a style='padding:0.1em;margin-left:0;' data-icon='info' class='btn btn1' onclick='showTrajectoryMessage(this)'>\u8be6\u60c5</a></div><div class='ui-block-c'><a style='padding:0.1em;margin-left:0;' data-icon='delete' class='btn btn1' onclick='TrajectoryDelete(this)'>\u5220\u9664</a></div></div></div>";$("#trajectory-list").append(e)}$(".btn").button();$("#trajectory-list").collapsibleset().trigger("create");$("#trajectory-list").collapsibleset("refresh")});
NavEvent.NavCtrlStatusTopic.subscribe(function(a){console.log(a);var b=getIndexFromArray(a.waypoint_name,NavEvent.data.WaypointList.waypoints),e="none";-1!=b&&(e=getWaypointIcon(b));var b=getIndexFromArray(NavEvent.data.CurrentPositionName,NavEvent.data.WaypointList.waypoints),c="none";-1!=b&&(c=getWaypointIcon(b));switch(a.status){case 1:$("#btn-waypoint-"+NavEvent.data.CurrentPositionName).parent().buttonMarkup({icon:c});$("#btn-waypoint-"+a.waypoint_name).parent().buttonMarkup({icon:"hrg-load"});
break;case 3:$("#btn-waypoint-"+a.waypoint_name).parent().buttonMarkup({icon:e});break;case 0:$(".btn1").prop("disabled",!1).removeClass("ui-disabled");break;case 4:$("#btn-waypoint-"+a.waypoint_name).parent().buttonMarkup({icon:e})}"all waypoints"!=a.waypoint_name&&(NavEvent.data.CurrentPositionName=a.waypoint_name)});$("#btn-add-waypoint").click(function(){var a=NavEvent.pose(parseFloat($("#pos_x")[0].value),parseFloat($("#pos_y")[0].value),parseFloat($("#ori_z")[0].value),parseFloat($("#ori_w")[0].value)),
b=$("#waypoints-action").val(),c=$("#timeout")[0].value,d=$("#area")[0].value,f=$("#waypoints-mode").val(),g="map";"map"==b?g="map":"timer"==b?g="timer":"publisher"==b?g="pub":"subscriber"==b?g="sub":"looper"==b&&(g="loop");var g=g+"-"+$("#name")[0].value,k=getIndexFromArray(g,NavEvent.data.TrajectoryList.trajectories);-1!==k?sweetAlert("Waypoint:"+g+" \u5728Trajectory\u5217\u8868\u4e2d\u5df2\u5360\u7528 \u4f4d\u4e8eTrajectory["+k+"]","","error"):(""==c&&(c=0),""==d&&(d=0),a=NavEvent.WaypointMessage(g,
a,parseFloat(d),parseFloat(c),f,b),NavEvent.WaypointAddTopic.publish(a),$.mobile.changePage("#hrg-navigation-setting-page",{transition:"slide"}))});$("#hrg-add-trajectory-page").live("pagehide",function(a,b){c=0;$("#waypoint-item select").remove()});var c=0;$("#btn-add-waypoint-item").click(function(){c++;var a="<select name='select-native-"+c+"'id='select-native-"+c+"' data-iconpos='right' onchange='DeleteSelectOption(this)'>"+NavEvent.data.WaypointsHtml+"</select>";$("#waypoint-item").append(a);
$("#select-native-"+c).selectmenu();$("#select-native-"+c).selectmenu("refresh");$("#select-native-"+c).parent().parent().hide();$("#select-native-"+c).parent().parent().fadeIn(2E3)});$("#btn-add-trajectory").click(function(){var a=!1,b=$("#trajectory-name")[0].value;if(""!=b){var e=getIndexFromArray(b,NavEvent.data.WaypointList.waypoints);if(-1!==e)sweetAlert("Waypoint:"+b+" \u5728Trajectory\u5217\u8868\u4e2d\u5df2\u5360\u7528 \u4f4d\u4e8eTrajectory["+e+"]","","error");else{for(var d=[],f=1;f<=c;f++)$("#select-native-"+
f)&&(a=!0,e=getIndexFromArray($("#select-native-"+f).find("option:selected").text(),NavEvent.data.WaypointList.waypoints),d.push(NavEvent.data.WaypointList.waypoints[e]));a?(a=NavEvent.TrajectoryMessage(b,d),NavEvent.TrajectoryAddTopic.publish(a),$.mobile.changePage("#hrg-navigation-setting",{transition:"slide"})):sweetAlert("\u672a\u8bbe\u5b9a\u8def\u70b9","","error");$.mobile.changePage("#hrg-navigation-setting-page",{transition:"slide"})}}});var f;$("#hrg-software-update-page").live("pageshow",
function(a,b){var c="<iframe src='http://hrgrobot.zicp.net?"+localStorage.serverIP+"'style='width:100%;height:150px;'frameborder='0' id='update-iframe'></iframe>";$("#update-content").append(c);$("#update-content").hide();$("#update-content").fadeIn(3E3);f=new WebSocket("ws://"+localStorage.serverIP+":3000");f.onopen=function(){console.log("success")};f.onmessage=function(a){console.log(a.data);a=JSON.parse(a.data);switch(a.cmd){case "software_update":a=new NavEvent.Msg(a.message),NavEvent.shellTopic.publish(a),
$("#update-info").text("")}}});$("#hrg-software-update-page").live("pagehide",function(a,b){$("#update-content iframe").remove();f.close()});$("#btn-software-update").click(function(){var a=new NavEvent.Msg(NavEvent.CmdEnum.Update);NavEvent.cmdTopic.publish(a);console.log(a)});$("#cancel").click(function(){var a=NavEvent.NavCtrlMessage(0,NavEvent.data.CurrentPositionName);NavEvent.NavCtrlTopic.publish(a)});$(".up").on("touchstart touchend",function(a){"touchstart"==a.type?(a.preventDefault(),$(this).attr("src",
"images/up1.png"),manual_control("up")):"touchend"==a.type&&($(this).attr("src","images/up.png"),manual_control_stop())});$(".down").on("touchstart touchend",function(a){"touchstart"==a.type?(a.preventDefault(),$(this).attr("src","images/down1.png"),manual_control("down")):"touchend"==a.type&&($(this).attr("src","images/down.png"),manual_control_stop())});$(".left").on("touchstart touchend",function(a){"touchstart"==a.type?(a.preventDefault(),$(this).attr("src","images/left1.png"),manual_control("left")):
"touchend"==a.type&&($(this).attr("src","images/left.png"),manual_control_stop())});$(".right").on("touchstart touchend",function(a){"touchstart"==a.type?(a.preventDefault(),$(this).attr("src","images/right1.png"),manual_control("right")):"touchend"==a.type&&($(this).attr("src","images/right.png"),manual_control_stop())});$(".stop").on("touchstart touchend",function(a){"touchstart"==a.type?(a.preventDefault(),$(this).attr("src","images/stopmove1.png"),manual_control("stop")):"touchend"==a.type&&($(this).attr("src",
"images/stopmove.png"),manual_control_stop())})});var CtrolTimer=null;function manual_control(a){null!=CtrolTimer&&(clearInterval(CtrolTimer),CtrolTimer=null);CtrolTimer=setInterval(function(){NavJobs.DirectionControl(a)},300)}function manual_control_stop(){null!=CtrolTimer&&(clearInterval(CtrolTimer),CtrolTimer=null);NavJobs.DirectionControl("stop")}
function DisableBrush(a){a.style.overflow="scroll";BrushJobs.DisableCanvasEdit();$("#map-scorll").text("\u542f\u7528\u753b\u7b14");$("#map-lines-add").prop("disabled",!0).addClass("ui-disabled");$("#map-lines-delete").prop("disabled",!0).addClass("ui-disabled")}
function EnableBrush(a){a.style.overflow="hidden";BrushJobs.EnableCanvasEdit("map-edit-canvas");$("#map-scorll").text("\u7981\u7528\u753b\u7b14");$("#map-lines-add").prop("disabled",!1).removeClass("ui-disabled");$("#map-lines-delete").prop("disabled",!1).removeClass("ui-disabled")}
function DiagnosticsCallback(a){console.log(a);for(var b=0;b<a.status.length;b++)if(a.status[b].name==NavEvent.diagnosticsNameEnum.Ros_Mode){switch(a.status[b].message){case NavEvent.CmdEnum.Navigation:NavEvent.data.NavigationMode!=NavEvent.CmdEnum.Navigation&&(console.log(a.status[b].message),NavEvent.data.NavigationMode=a.status[b].message,$(".btn-start-create-map").text("\u5f00\u542f\u5efa\u56fe"),$(".btn-start-create-map").buttonMarkup({icon:"hrg-stop"}),NavEvent.data.SaveMapEditFlag&&(NavEvent.data.SaveMapEditFlag=
!1,$("#map-edit-save").buttonMarkup({icon:"hrg-save"}),$.mobile.changePage("#hrg-menu-page",{transition:"slide"})));break;case NavEvent.CmdEnum.Gmapping:NavEvent.data.NavigationMode!=NavEvent.CmdEnum.Gmapping&&(console.log(a.status[b].message),NavEvent.data.NavigationMode=a.status[b].message,$(".btn-start-create-map").text("\u5173\u95ed\u5efa\u56fe"),$(".btn-start-create-map").buttonMarkup({icon:"hrg-start"}),$.mobile.changePage("#hrg-map-wizard-second",{transition:"slide"}));break;case NavEvent.CmdEnum.Coverting:NavEvent.data.NavigationMode!=
NavEvent.CmdEnum.Coverting&&(console.log(a.status[b].message),NavEvent.data.NavigationMode=a.status[b].message,$(".btn-start-create-map").text("\u6a21\u5f0f\u5207\u6362\u4e2d..."),$(".btn-start-create-map").buttonMarkup({icon:"hrg-load"}))}break}}
function ShellFeedbackCallBack(a){console.log(a);switch(a.data){case "joy_on":$("#handle-switch").text("\u624b\u67c4\u5173\u95ed");$("#handle-switch").buttonMarkup({icon:"hrg-start"});break;case "joy_off":$("#handle-switch").text("\u624b\u67c4\u5f00\u542f");$("#handle-switch").buttonMarkup({icon:"hrg-stop"});break;case "save_map":if(NavEvent.data.CreateMapFlag){var b=new NavEvent.Msg(NavEvent.CmdEnum.LoadMap);NavEvent.cmdTopic.publish(b);a=new NavEvent.Msg(NavEvent.CmdEnum.SaveMapEdit);NavEvent.cmdTopic.publish(a)}break;
case "save_map_edit":NavEvent.data.CreateMapFlag&&(b=new NavEvent.Msg(NavEvent.CmdEnum.LoadMapEdit),NavEvent.cmdTopic.publish(b),console.log(b),$("#map-save").buttonMarkup({icon:"hrg-save"}),$.mobile.changePage("#hrg-map-wizard-third",{transition:"slide"}));break;case "save_as_map_edit":NavEvent.data.CreateMapFlag&&(NavEvent.data.SaveMapEditFlag=!0,NavJobs.Navigation());break;default:switch(b=a.data.split(/[ :]/),b[0]){case "version":$(".version").html(b[1]);break;case "user_status":256==b[1]?$("#btn-plc").buttonMarkup({icon:"hty-normal-run"}):
257==b[1]?$("#btn-plc").buttonMarkup({icon:"hty-error-run"}):0==b[1]?$("#btn-plc").buttonMarkup({icon:"hty-stop"}):1==b[1]&&$("#btn-plc").buttonMarkup({icon:"hty-error-stop"});break;case "user_auth":NavEvent.data.MachineModel=b[1];a=new NavEvent.Msg(NavEvent.CmdEnum.Joystick);NavEvent.shellTopic.publish(a);a=new NavEvent.Msg(NavEvent.CmdEnum.Version);NavEvent.cmdTopic.publish(a);"true"==b[1]?$.mobile.changePage("#hrg-login-page",{transition:"slide"}):$.mobile.changePage("#hrg-navigation-main-page",
{transition:"slide"});break;case "software_update":document.getElementById("update-info").innerHTML+="<p>"+a.data.substring(b[0].length+1,a.data.length)+"</p>";break;case "dbparam":CurrentMap=b[1];$(".current-map-name").text(b[1]);a=document.getElementById("map-select").innerHTML="";for(var d=1;d<b.length;d++)a+="<option value='"+b[d]+"'>"+b[d]+"</option>";$("#map-select").append(a);$("#map-select").selectmenu();$("#map-select").selectmenu("refresh");MapCurrentCmd==MapCmdEnum.map_insert?CurrentMap==
CreatMap&&($("#btn-map-insert").buttonMarkup({icon:"plus"}),sweetAlert("\u521b\u5efa\u6210\u529f","","success")):MapCurrentCmd==MapCmdEnum.map_update&&CurrentMap==SelectMap&&($("#hrg-map-selected-popup").popup("close"),NavJobs.RemoveMap("nav"),NavJobs.LoadMap(800,800,"nav"),$("#nav canvas").on("taphold",function(){$("#hrg-manual-control-popup").popup();$("#hrg-manual-control-popup").popup("open")}));SelectMap=CreatMap=MapCurrentCmd=""}}}
function DeleteSelectOption(a){-1==$(a).val()&&$(a).parent().parent().fadeOut(2E3,function(){$(a).remove()})}function goPostion(a){$(".btn1").prop("disabled",!0).addClass("ui-disabled");a=$(a).parent().parent().parent()[0].id;a=a.substring(3,a.length);var b=NavEvent.NavCtrlMessage(1,a);NavEvent.data.CurrentPositionName=a;getIndexFromArray(a,NavEvent.data.WaypointList.waypoints);NavEvent.NavCtrlTopic.publish(b)}
function showTrajectoryMessage(a){$("#trajectory-info-list")[0].innerHTML="";$.mobile.changePage("#hrg-trajectory-info-page",{transition:"slide"});a=$(a).parent().parent().parent()[0].id;a=a.substring(3,a.length);$("#trajectory-info-name").val(a);a=getIndexFromArray(a,NavEvent.data.TrajectoryList.trajectories);for(var b=0;b<NavEvent.data.TrajectoryList.trajectories[a].waypoints.length;b++){var d=NavEvent.data.TrajectoryList.trajectories[a].waypoints[b].name,c="location";"map"==NavEvent.data.TrajectoryList.trajectories[a].waypoints[b].header.frame_id?
c="location":"timer"==NavEvent.data.TrajectoryList.trajectories[a].waypoints[b].header.frame_id?c="clock":"publisher"==NavEvent.data.TrajectoryList.trajectories[a].waypoints[b].header.frame_id?c="navigation":"subscriber"==NavEvent.data.TrajectoryList.trajectories[a].waypoints[b].header.frame_id?c="star":"looper"==NavEvent.data.TrajectoryList.trajectories[a].waypoints[b].header.frame_id&&(c="recycle");d="<a style='padding:0.1em;margin-left:0;' data-icon='"+c+"' class='btn' onclick='showWaypointMessage(this)'>"+
d+"</a></div>";$("#trajectory-info-list").append(d);$(".btn").button()}}
function showWaypointMessage(a){$("#waypoint-info-list")[0].innerHTML="";$.mobile.changePage("#hrg-waypoints-info-page",{transition:"slide"});a=$(a)[0].innerHTML;$("#hrg-waypoints-info-page h1")[0].innerHTML=a;a=getIndexFromArray(a,NavEvent.data.WaypointList.waypoints);var b=NavEvent.data.WaypointList.waypoints[a];a=" <div class='ui-grid-a' ><div class='ui-block-a'><a style='padding:0.1em;margin-left:0;' data-icon='hrg-mark' class='btn '>Name</a></div><div class='ui-block-b'><a style='padding:0.1em;margin-left:0;' data-icon='hrg-value' class='btn' >"+b.name+
"</a></div></div>";var d=" <div class='ui-grid-a' ><div class='ui-block-a'><a style='padding:0.1em;margin-left:0;' data-icon='hrg-mark' class='btn'>Area</a></div><div class='ui-block-b'><a style='padding:0.1em;margin-left:0;' data-icon='hrg-value' class='btn' >"+b.close_enough+"</a></div></div>",c=" <div class='ui-grid-a' ><div class='ui-block-a'><a style='padding:0.1em;margin-left:0;' data-icon='hrg-mark' class='btn'>Timeout</a></div><div class='ui-block-b'><a style='padding:0.1em;margin-left:0;' data-icon='hrg-value' class='btn' >"+
b.goal_timeout+"</a></div></div>",f=" <div class='ui-grid-a' ><div class='ui-block-a'><a style='padding:0.1em;margin-left:0;' data-icon='hrg-mark' class='btn'>Mode</a></div><div class='ui-block-b'><a style='padding:0.1em;margin-left:0;' data-icon='hrg-value' class='btn' >"+b.failure_mode+"</a></div></div>",b=" <div class='ui-grid-a' ><div class='ui-block-a'><a style='padding:0.1em;margin-left:0;' data-icon='hrg-mark' class='btn'>Action</a></div><div class='ui-block-b'><a style='padding:0.1em;margin-left:0;' data-icon='hrg-value' class='btn' >"+
b.header.frame_id+"</a></div></div>";$("#waypoint-info-list").append(a);$("#waypoint-info-list").append(d);$("#waypoint-info-list").append(c);$("#waypoint-info-list").append(f);$("#waypoint-info-list").append(b);$(".btn").button()}
function WaypointDelete(a){var b=$(a).parent().parent().parent()[0].id,d=b.substring(3,b.length);$($(a).parent().parent().parent()).fadeTo("slow",.01,function(){$(this).slideUp("slow",function(){var a=getIndexFromArray(d,NavEvent.data.WaypointList.waypoints);NavEvent.WaypointRemoveTopic.publish(NavEvent.data.WaypointList.waypoints[a]);$(this).remove()})})}
function TrajectoryDelete(a){var b=$(a).parent().parent().parent()[0].id,d=b.substring(3,b.length);$($(a).parent().parent().parent()).fadeTo("slow",.01,function(){$(this).slideUp("slow",function(){var a=getIndexFromArray(d,NavEvent.data.TrajectoryList.trajectories);NavEvent.TrajectoryRemoveTopic.publish(NavEvent.data.TrajectoryList.trajectories[a]);$(this).remove()})})}
function IpCheck(a){str=a;str=str.match(/(\d+)\.(\d+)\.(\d+)\.(\d+)/g);return null==str?!1:255<RegExp.$1||255<RegExp.$2||255<RegExp.$3||255<RegExp.$4?!1:!0}function getIndexFromArray(a,b){try{for(var d=-1,c=0;c<b.length;c++)if(a==b[c].name){d=c;break}return d}catch(f){return sweetAlert("\u83b7\u53d6\u7ad9\u70b9\u4fe1\u606f\u5931\u8d25","","error"),-1}}
function DiagnosisPageCallBack(a){NavJobs.unsubscribeDiagnostics(DiagnosisPageCallBack);for(var b=0;b<a.status.length;b++){var d="<div data-role='collapsible'><h3>"+a.status[b].name+"</h3><p>"+a.status[b].message+"</p></div>";$("#diagnostics-list").append(d)}$("#diagnostics-list").trigger("create");$("#diagnostics-list").collapsibleset("refresh");$("#hrg-diagnosis-content img").hide()}
function getWaypointIcon(a){var b="none";"map"==NavEvent.data.WaypointList.waypoints[a].header.frame_id?b="location":"timer"==NavEvent.data.WaypointList.waypoints[a].header.frame_id?b="clock":"publisher"==NavEvent.data.WaypointList.waypoints[a].header.frame_id?b="navigation":"subscriber"==NavEvent.data.WaypointList.waypoints[a].header.frame_id?b="star":"looper"==NavEvent.data.WaypointList.waypoints[a].header.frame_id&&(b="recycle");return b};