var MysqlEvent=NavEvent||{REVISION:"0.0.1.0-2016-11.15"};
MysqlEvent.status={LoginSuccess:0,LoginFail_NotExist:-1,LoginFail_LoginedIn:-2,LoginFail_WrongPwd:-3,RegisterSuccess:1,RegisterFail:-4,RegisterFail_Exist:-5,RegisterFail_InvalidCode:-6,LogoutSuccess:2,LogoutFail:-7,UpdataSuccess:3,UpdataFail:-8,GenerateCodeSuccess:4,GenerateCodeFail:-9,InvalidAuthCode:-10,RegisterFail_CodeOutOfDate:-11,UpdateAuthSuccess:5,UpdateAuthFail:-12,UpdateAuthFail_Denied:-13,StoreOpRecordSuccess:6,StoreOpRecordFail:-14,QueryOpRecordSuccess:7,QueryOpRecordFail:-15};
MysqlEvent.HtmlID={login_name:"#login-name",login_password:"#login-password",register_name:"#register-name",register_password:"#register-password",register_password_agin:"#register-password-agin",register_auth_code:"#register-auth-code",old_password:"#old-password",new_password:"#new-password",confirm_password:"#confirm-password",user_table:"#hty-user-table",history_table:"#hty-history-table"};
$(function(){function l(a,b){$.ajax({type:"post",url:"http://"+window.location.hostname+":8808/store_record",data:{time:m(new Date,"yyyy-M-d hh:mm:ss"),username:a,operation:b},async:!0,success:function(a){console.log(a)},dataType:"json"})}function h(a){return/^(\w){6,20}$/.exec(a)?!0:!1}function k(a,b){var c=$(b)[0].innerHTML="",d=[],e;for(e in a[0])c+="<th data-priority='1'>"+e+"</th>",d.push(e);c=" <thead><tr>"+c+"</tr></thead>";$(b).append(c);c="";for(e=0;e<a.length;e++){for(var f="",g=0;g<d.length;g++)f+=
"<td>"+a[e][d[g]]+"</td>";c+="<tr>"+f+"</tr>"}d="<tbody>"+c+"</tbody>";$(b).append(d)}function m(a,b){var c=function(a){return(a+"").replace(/^(\d)$/,"0$1")},d={yyyy:a.getFullYear(),yy:a.getFullYear().toString().substring(2),M:a.getMonth()+1,MM:c(a.getMonth()+1),d:a.getDate(),dd:c(a.getDate()),hh:a.getHours(),mm:a.getMinutes(),ss:a.getSeconds()};b||(b="yyyy-MM-dd hh:mm:ss");return b.replace(/([a-z])(\1)*/ig,function(a){return d[a]})}$("#login").click(function(){var a=$(MysqlEvent.HtmlID.login_name)[0].value,
b=$(MysqlEvent.HtmlID.login_password)[0].value;$.ajax({type:"post",url:"http://"+window.location.hostname+":8808/login",data:{username:a,password:b},async:!0,success:function(c){console.log(c);c.status==MysqlEvent.status.LoginSuccess?(NavEvent.data.LoginName=a,NavEvent.data.LoginPassword=b,NavEvent.data.Auth=c.auth,$(".current-user").html(c.auth),$.mobile.changePage("#hrg-navigation-main-page",{transition:"slide"}),l(a,JSON.stringify({action:"login"}))):c.status==MysqlEvent.status.LoginFail_NotExist?
sweetAlert("\u7528\u6237\u540d\u4e0d\u5b58\u5728","","error"):c.status==MysqlEvent.status.LoginFail_LoginedIn?sweetAlert("\u8be5\u7528\u6237\u5df2\u5728\u5176\u4ed6\u8bbe\u5907\u767b\u5f55","","warning"):c.status==MysqlEvent.status.LoginFail_WrongPwd&&sweetAlert("\u5bc6\u7801\u9519\u8bef","","error")},dataType:"json"})});$("#logout").click(function(){$.ajax({type:"post",url:"http://"+window.location.hostname+":8808/logout",data:{username:NavEvent.data.LoginName},async:!0,success:function(a){console.log(a);
a.status==MysqlEvent.status.LogoutSuccess?(NavEvent.data.LoginName="",NavEvent.data.LoginPassword="",NavEvent.data.Auth="",$(MysqlEvent.HtmlID.login_name)[0].value="",$(MysqlEvent.HtmlID.login_password)[0].value="",$.mobile.changePage("#hrg-login-page",{transition:"slide"})):a.status==MysqlEvent.status.LogoutFail&&sweetAlert("\u6ce8\u9500\u5931\u8d25","","error")},dataType:"json"})});$("#get").click(function(){$.ajax({type:"get",url:"http://"+window.location.hostname+":8808/user_select",async:!0,
success:function(a){console.log(a);k(a,MysqlEvent.HtmlID.user_table);$.mobile.changePage("#hty-user-table-page",{transition:"slide"})},dataType:"json"})});$("#btn-register").click(function(){var a=$(MysqlEvent.HtmlID.register_name)[0].value,b=$(MysqlEvent.HtmlID.register_password)[0].value,c=$(MysqlEvent.HtmlID.register_auth_code)[0].value;/^[a-zA-Z]{1}([a-zA-Z0-9]|[._]){4,19}$/.exec(a)?""==c?sweetAlert("\u6388\u6743\u7801\u4e0d\u80fd\u4e3a\u7a7a","","warning"):"hitrobot"!=c&&32!=c.length?sweetAlert("\u6388\u6743\u7801\u4e0d\u5408\u6cd5",
"","warning"):h(b)?b!=$(MysqlEvent.HtmlID.register_password_agin)[0].value?sweetAlert("\u5bc6\u7801\u4e0d\u4e00\u81f4","","error"):$.ajax({type:"post",url:"http://"+window.location.hostname+":8808/register",data:{username:a,password:b,authCode:c},async:!0,success:function(a){a.status==MysqlEvent.status.RegisterSuccess?$.mobile.changePage("#hrg-login-page",{transition:"slide"}):a.status==MysqlEvent.status.RegisterFail?sweetAlert("\u6ce8\u518c\u5931\u8d25","","error"):a.status==MysqlEvent.status.RegisterFail_Exist&&
sweetAlert("\u6ce8\u518c\u5931\u8d25 \u7528\u6237\u540d\u5df2\u5b58\u5728","","error")},dataType:"json"}):sweetAlert("\u5bc6\u7801\u4e0d\u5408\u6cd5","","warning"):sweetAlert("\u7528\u6237\u540d\u4e0d\u5408\u6cd5","","warning")});$("#btn-change-login-password").click(function(){if($(MysqlEvent.HtmlID.old_password)[0].value!=NavEvent.data.LoginPassword)sweetAlert("\u539f\u5bc6\u7801\u8f93\u5165\u9519\u8bef","","error");else if(h($(MysqlEvent.HtmlID.new_password)[0].value))if($("#new-password")[0].value!=
$(MysqlEvent.HtmlID.confirm_password)[0].value)sweetAlert("\u8f93\u5165\u5bc6\u7801\u4e0d\u4e00\u81f4","","error");else{var a=NavEvent.data.LoginName,b=$(MysqlEvent.HtmlID.new_password)[0].value;$.ajax({type:"post",url:"http://"+window.location.hostname+":8808/update",data:{username:a,password:b},async:!0,success:function(a){console.log(a);a.status==MysqlEvent.status.UpdataSuccess?(NavEvent.data.LoginPassword=b,sweetAlert("\u4fee\u6539\u6210\u529f","","success"),$("#hrg-change-password-popup").popup("close")):
a.status==db_status.UpdataFail&&sweetAlert("\u4fee\u6539\u5931\u8d25","","error")},dataType:"json"})}else sweetAlert("\u65b0\u5bc6\u7801\u4e0d\u5408\u6cd5","","warning")});$("#btn-get-auth-code").click(function(){$(this).buttonMarkup({icon:"hrg-load"});var a=NavEvent.data.LoginName,b=$("#auth-code-select").val();$.ajax({type:"post",url:"http://"+window.location.hostname+":8808/code",data:{username:a,auth:b},async:!0,success:function(a){console.log(a);$("#btn-get-auth-code").buttonMarkup({icon:"star"});
a.status==MysqlEvent.status.GenerateCodeSuccess?$("#new-auth-code").val(a.authcode):a.status==MysqlEvent.status.GenerateCodeFail&&sweetAlert(a.message,"","error")},dataType:"json"})});$("#hty-history-search-page").live("pageshow",function(a,b){if("hty-user-manger-page"==b.prevPage[0].id){var c="<option value='-1'>ALL</option>";$.ajax({type:"get",url:"http://"+window.location.hostname+":8808/get_users",async:!0,success:function(a){console.log(a);for(var b=0;b<a.users.length;b++)c+="<option value='"+
a.users[b]+"'>"+a.users[b]+"</option>";$("#hty-users-list").append(c);$("#hty-users-list").selectmenu();$("#hty-users-list").selectmenu("refresh")},dataType:"json"})}});$("#hty-history-search-page").live("pagehide",function(a,b){"hrg-user-manger-page"==b.toPage[0].id&&($("#hty-users-list")[0].innerHTML="")});$("#btn-history-search").click(function(){var a=$("#dtl")[0].value,b=$("#dt2")[0].value,c=$("#hty-users-list").find("option:selected").text(),a=a.replace("T"," "),b=b.replace("T"," ");console.log(a);
console.log(b);$.ajax({type:"post",url:"http://"+window.location.hostname+":8808/query_op",data:{username:c,start:a,end:b},async:!0,success:function(a){a.status==MysqlEvent.status.QueryOpRecordSuccess&&(k(a.records,MysqlEvent.HtmlID.history_table),$.mobile.changePage("#hty-history-page",{transition:"slide"}))},dataType:"json"})});$("#btn-test").click(function(){$.ajax({type:"get",url:"http://"+window.location.hostname+":8808/download",async:!0,success:function(a){console.log(a)},dataType:"json"})});
window.onbeforeunload=function(a){""!=NavEvent.data.LoginName&&$("#logout").click()}});