(cl:defpackage cob_light-srv
  (:use )
  (:export
   "STOPLIGHTMODE"
   "<STOPLIGHTMODE-REQUEST>"
   "STOPLIGHTMODE-REQUEST"
   "<STOPLIGHTMODE-RESPONSE>"
   "STOPLIGHTMODE-RESPONSE"
   "SETLIGHTMODE"
   "<SETLIGHTMODE-REQUEST>"
   "SETLIGHTMODE-REQUEST"
   "<SETLIGHTMODE-RESPONSE>"
   "SETLIGHTMODE-RESPONSE"
  ))

