# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from scheduling_msgs/NewTask.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class NewTask(genpy.Message):
  _md5sum = "eb9b965ae452a7d2f5b77f9dcab2f6e9"
  _type = "scheduling_msgs/NewTask"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32 taskID
int32 source_stationID
int32 source_action
int32 destination_stationID
int32 destination_action


"""
  __slots__ = ['taskID','source_stationID','source_action','destination_stationID','destination_action']
  _slot_types = ['int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       taskID,source_stationID,source_action,destination_stationID,destination_action

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(NewTask, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.taskID is None:
        self.taskID = 0
      if self.source_stationID is None:
        self.source_stationID = 0
      if self.source_action is None:
        self.source_action = 0
      if self.destination_stationID is None:
        self.destination_stationID = 0
      if self.destination_action is None:
        self.destination_action = 0
    else:
      self.taskID = 0
      self.source_stationID = 0
      self.source_action = 0
      self.destination_stationID = 0
      self.destination_action = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_5i.pack(_x.taskID, _x.source_stationID, _x.source_action, _x.destination_stationID, _x.destination_action))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.taskID, _x.source_stationID, _x.source_action, _x.destination_stationID, _x.destination_action,) = _struct_5i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_5i.pack(_x.taskID, _x.source_stationID, _x.source_action, _x.destination_stationID, _x.destination_action))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.taskID, _x.source_stationID, _x.source_action, _x.destination_stationID, _x.destination_action,) = _struct_5i.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_5i = struct.Struct("<5i")
