// Generated by gencpp from file cob_mimic/SetMimicFeedback.msg
// DO NOT EDIT!


#ifndef COB_MIMIC_MESSAGE_SETMIMICFEEDBACK_H
#define COB_MIMIC_MESSAGE_SETMIMICFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cob_mimic
{
template <class ContainerAllocator>
struct SetMimicFeedback_
{
  typedef SetMimicFeedback_<ContainerAllocator> Type;

  SetMimicFeedback_()
    {
    }
  SetMimicFeedback_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }






  typedef boost::shared_ptr< ::cob_mimic::SetMimicFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cob_mimic::SetMimicFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct SetMimicFeedback_

typedef ::cob_mimic::SetMimicFeedback_<std::allocator<void> > SetMimicFeedback;

typedef boost::shared_ptr< ::cob_mimic::SetMimicFeedback > SetMimicFeedbackPtr;
typedef boost::shared_ptr< ::cob_mimic::SetMimicFeedback const> SetMimicFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cob_mimic::SetMimicFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cob_mimic::SetMimicFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cob_mimic

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'cob_mimic': ['/home/ouiyeah/catkin_ws/devel/share/cob_mimic/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cob_mimic::SetMimicFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cob_mimic::SetMimicFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_mimic::SetMimicFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_mimic::SetMimicFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_mimic::SetMimicFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_mimic::SetMimicFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cob_mimic::SetMimicFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::cob_mimic::SetMimicFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::cob_mimic::SetMimicFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cob_mimic/SetMimicFeedback";
  }

  static const char* value(const ::cob_mimic::SetMimicFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cob_mimic::SetMimicFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
";
  }

  static const char* value(const ::cob_mimic::SetMimicFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cob_mimic::SetMimicFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetMimicFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cob_mimic::SetMimicFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::cob_mimic::SetMimicFeedback_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // COB_MIMIC_MESSAGE_SETMIMICFEEDBACK_H
