// Generated by gencpp from file cob_mimic/SetMimicGoal.msg
// DO NOT EDIT!


#ifndef COB_MIMIC_MESSAGE_SETMIMICGOAL_H
#define COB_MIMIC_MESSAGE_SETMIMICGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace cob_mimic
{
template <class ContainerAllocator>
struct SetMimicGoal_
{
  typedef SetMimicGoal_<ContainerAllocator> Type;

  SetMimicGoal_()
    : mimic()
    , speed(0.0)
    , repeat(0)  {
    }
  SetMimicGoal_(const ContainerAllocator& _alloc)
    : mimic(_alloc)
    , speed(0.0)
    , repeat(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _mimic_type;
  _mimic_type mimic;

   typedef float _speed_type;
  _speed_type speed;

   typedef int64_t _repeat_type;
  _repeat_type repeat;




  typedef boost::shared_ptr< ::cob_mimic::SetMimicGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cob_mimic::SetMimicGoal_<ContainerAllocator> const> ConstPtr;

}; // struct SetMimicGoal_

typedef ::cob_mimic::SetMimicGoal_<std::allocator<void> > SetMimicGoal;

typedef boost::shared_ptr< ::cob_mimic::SetMimicGoal > SetMimicGoalPtr;
typedef boost::shared_ptr< ::cob_mimic::SetMimicGoal const> SetMimicGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::cob_mimic::SetMimicGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::cob_mimic::SetMimicGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace cob_mimic

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'cob_mimic': ['/home/ouiyeah/catkin_ws/devel/share/cob_mimic/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::cob_mimic::SetMimicGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::cob_mimic::SetMimicGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_mimic::SetMimicGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::cob_mimic::SetMimicGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_mimic::SetMimicGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::cob_mimic::SetMimicGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::cob_mimic::SetMimicGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6046fb0fc821e346cac6470d0911e088";
  }

  static const char* value(const ::cob_mimic::SetMimicGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6046fb0fc821e346ULL;
  static const uint64_t static_value2 = 0xcac6470d0911e088ULL;
};

template<class ContainerAllocator>
struct DataType< ::cob_mimic::SetMimicGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "cob_mimic/SetMimicGoal";
  }

  static const char* value(const ::cob_mimic::SetMimicGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::cob_mimic::SetMimicGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
string mimic\n\
float32 speed\n\
int64 repeat\n\
";
  }

  static const char* value(const ::cob_mimic::SetMimicGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::cob_mimic::SetMimicGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mimic);
      stream.next(m.speed);
      stream.next(m.repeat);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetMimicGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cob_mimic::SetMimicGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::cob_mimic::SetMimicGoal_<ContainerAllocator>& v)
  {
    s << indent << "mimic: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.mimic);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "repeat: ";
    Printer<int64_t>::stream(s, indent + "  ", v.repeat);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COB_MIMIC_MESSAGE_SETMIMICGOAL_H
