// Generated by gencpp from file scheduling_msgs/AddProductionMaterial.msg
// DO NOT EDIT!


#ifndef SCHEDULING_MSGS_MESSAGE_ADDPRODUCTIONMATERIAL_H
#define SCHEDULING_MSGS_MESSAGE_ADDPRODUCTIONMATERIAL_H

#include <ros/service_traits.h>


#include <scheduling_msgs/AddProductionMaterialRequest.h>
#include <scheduling_msgs/AddProductionMaterialResponse.h>


namespace scheduling_msgs
{

struct AddProductionMaterial
{

typedef AddProductionMaterialRequest Request;
typedef AddProductionMaterialResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddProductionMaterial
} // namespace scheduling_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scheduling_msgs::AddProductionMaterial > {
  static const char* value()
  {
    return "42e2dd3ce9a8829f53d3b4b242875ecf";
  }

  static const char* value(const ::scheduling_msgs::AddProductionMaterial&) { return value(); }
};

template<>
struct DataType< ::scheduling_msgs::AddProductionMaterial > {
  static const char* value()
  {
    return "scheduling_msgs/AddProductionMaterial";
  }

  static const char* value(const ::scheduling_msgs::AddProductionMaterial&) { return value(); }
};


// service_traits::MD5Sum< ::scheduling_msgs::AddProductionMaterialRequest> should match 
// service_traits::MD5Sum< ::scheduling_msgs::AddProductionMaterial > 
template<>
struct MD5Sum< ::scheduling_msgs::AddProductionMaterialRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scheduling_msgs::AddProductionMaterial >::value();
  }
  static const char* value(const ::scheduling_msgs::AddProductionMaterialRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scheduling_msgs::AddProductionMaterialRequest> should match 
// service_traits::DataType< ::scheduling_msgs::AddProductionMaterial > 
template<>
struct DataType< ::scheduling_msgs::AddProductionMaterialRequest>
{
  static const char* value()
  {
    return DataType< ::scheduling_msgs::AddProductionMaterial >::value();
  }
  static const char* value(const ::scheduling_msgs::AddProductionMaterialRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scheduling_msgs::AddProductionMaterialResponse> should match 
// service_traits::MD5Sum< ::scheduling_msgs::AddProductionMaterial > 
template<>
struct MD5Sum< ::scheduling_msgs::AddProductionMaterialResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scheduling_msgs::AddProductionMaterial >::value();
  }
  static const char* value(const ::scheduling_msgs::AddProductionMaterialResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scheduling_msgs::AddProductionMaterialResponse> should match 
// service_traits::DataType< ::scheduling_msgs::AddProductionMaterial > 
template<>
struct DataType< ::scheduling_msgs::AddProductionMaterialResponse>
{
  static const char* value()
  {
    return DataType< ::scheduling_msgs::AddProductionMaterial >::value();
  }
  static const char* value(const ::scheduling_msgs::AddProductionMaterialResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCHEDULING_MSGS_MESSAGE_ADDPRODUCTIONMATERIAL_H
