// Generated by gencpp from file scheduling_msgs/AgvList.msg
// DO NOT EDIT!


#ifndef SCHEDULING_MSGS_MESSAGE_AGVLIST_H
#define SCHEDULING_MSGS_MESSAGE_AGVLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <scheduling_msgs/Agv.h>

namespace scheduling_msgs
{
template <class ContainerAllocator>
struct AgvList_
{
  typedef AgvList_<ContainerAllocator> Type;

  AgvList_()
    : agvList()  {
    }
  AgvList_(const ContainerAllocator& _alloc)
    : agvList(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::scheduling_msgs::Agv_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::scheduling_msgs::Agv_<ContainerAllocator> >::other >  _agvList_type;
  _agvList_type agvList;




  typedef boost::shared_ptr< ::scheduling_msgs::AgvList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scheduling_msgs::AgvList_<ContainerAllocator> const> ConstPtr;

}; // struct AgvList_

typedef ::scheduling_msgs::AgvList_<std::allocator<void> > AgvList;

typedef boost::shared_ptr< ::scheduling_msgs::AgvList > AgvListPtr;
typedef boost::shared_ptr< ::scheduling_msgs::AgvList const> AgvListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scheduling_msgs::AgvList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scheduling_msgs::AgvList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace scheduling_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'scheduling_msgs': ['/home/ouiyeah/catkin_ws/src/hitrobot/scheduling_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::scheduling_msgs::AgvList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scheduling_msgs::AgvList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scheduling_msgs::AgvList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scheduling_msgs::AgvList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scheduling_msgs::AgvList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scheduling_msgs::AgvList_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scheduling_msgs::AgvList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ab4fe433cd794e9c63428ead5835410";
  }

  static const char* value(const ::scheduling_msgs::AgvList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ab4fe433cd794e9ULL;
  static const uint64_t static_value2 = 0xc63428ead5835410ULL;
};

template<class ContainerAllocator>
struct DataType< ::scheduling_msgs::AgvList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scheduling_msgs/AgvList";
  }

  static const char* value(const ::scheduling_msgs::AgvList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scheduling_msgs::AgvList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Agv[] agvList\n\
================================================================================\n\
MSG: scheduling_msgs/Agv\n\
int32 agvID\n\
string agvName\n\
bool isWorking\n\
bool isAgvBoot\n\
#bool isTaskOverTime\n\
int32 errorInfo\n\
#0 : no error\n\
#1 : obstacle\n\
#2 : battery low\n\
#3 : navigation error \n\
string working_station_name\n\
geometry_msgs/Pose pose\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::scheduling_msgs::AgvList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scheduling_msgs::AgvList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.agvList);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AgvList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scheduling_msgs::AgvList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scheduling_msgs::AgvList_<ContainerAllocator>& v)
  {
    s << indent << "agvList[]" << std::endl;
    for (size_t i = 0; i < v.agvList.size(); ++i)
    {
      s << indent << "  agvList[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::scheduling_msgs::Agv_<ContainerAllocator> >::stream(s, indent + "    ", v.agvList[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCHEDULING_MSGS_MESSAGE_AGVLIST_H
