// Generated by gencpp from file scheduling_msgs/DeleteProductionMaterialRequest.msg
// DO NOT EDIT!


#ifndef SCHEDULING_MSGS_MESSAGE_DELETEPRODUCTIONMATERIALREQUEST_H
#define SCHEDULING_MSGS_MESSAGE_DELETEPRODUCTIONMATERIALREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scheduling_msgs
{
template <class ContainerAllocator>
struct DeleteProductionMaterialRequest_
{
  typedef DeleteProductionMaterialRequest_<ContainerAllocator> Type;

  DeleteProductionMaterialRequest_()
    : machine()
    , model()  {
    }
  DeleteProductionMaterialRequest_(const ContainerAllocator& _alloc)
    : machine(_alloc)
    , model(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _machine_type;
  _machine_type machine;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _model_type;
  _model_type model;




  typedef boost::shared_ptr< ::scheduling_msgs::DeleteProductionMaterialRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scheduling_msgs::DeleteProductionMaterialRequest_<ContainerAllocator> const> ConstPtr;

}; // struct DeleteProductionMaterialRequest_

typedef ::scheduling_msgs::DeleteProductionMaterialRequest_<std::allocator<void> > DeleteProductionMaterialRequest;

typedef boost::shared_ptr< ::scheduling_msgs::DeleteProductionMaterialRequest > DeleteProductionMaterialRequestPtr;
typedef boost::shared_ptr< ::scheduling_msgs::DeleteProductionMaterialRequest const> DeleteProductionMaterialRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scheduling_msgs::DeleteProductionMaterialRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scheduling_msgs::DeleteProductionMaterialRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace scheduling_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'scheduling_msgs': ['/home/ouiyeah/catkin_ws/src/hitrobot/scheduling_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::scheduling_msgs::DeleteProductionMaterialRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scheduling_msgs::DeleteProductionMaterialRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scheduling_msgs::DeleteProductionMaterialRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scheduling_msgs::DeleteProductionMaterialRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scheduling_msgs::DeleteProductionMaterialRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scheduling_msgs::DeleteProductionMaterialRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scheduling_msgs::DeleteProductionMaterialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b2f5792d81a976eb9be050db606e3f9d";
  }

  static const char* value(const ::scheduling_msgs::DeleteProductionMaterialRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb2f5792d81a976ebULL;
  static const uint64_t static_value2 = 0x9be050db606e3f9dULL;
};

template<class ContainerAllocator>
struct DataType< ::scheduling_msgs::DeleteProductionMaterialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scheduling_msgs/DeleteProductionMaterialRequest";
  }

  static const char* value(const ::scheduling_msgs::DeleteProductionMaterialRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scheduling_msgs::DeleteProductionMaterialRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
string machine\n\
string model\n\
";
  }

  static const char* value(const ::scheduling_msgs::DeleteProductionMaterialRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scheduling_msgs::DeleteProductionMaterialRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.machine);
      stream.next(m.model);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct DeleteProductionMaterialRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scheduling_msgs::DeleteProductionMaterialRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scheduling_msgs::DeleteProductionMaterialRequest_<ContainerAllocator>& v)
  {
    s << indent << "machine: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.machine);
    s << indent << "model: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.model);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCHEDULING_MSGS_MESSAGE_DELETEPRODUCTIONMATERIALREQUEST_H
