// Generated by gencpp from file scheduling_msgs/QueryPathOnly.msg
// DO NOT EDIT!


#ifndef SCHEDULING_MSGS_MESSAGE_QUERYPATHONLY_H
#define SCHEDULING_MSGS_MESSAGE_QUERYPATHONLY_H

#include <ros/service_traits.h>


#include <scheduling_msgs/QueryPathOnlyRequest.h>
#include <scheduling_msgs/QueryPathOnlyResponse.h>


namespace scheduling_msgs
{

struct QueryPathOnly
{

typedef QueryPathOnlyRequest Request;
typedef QueryPathOnlyResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct QueryPathOnly
} // namespace scheduling_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scheduling_msgs::QueryPathOnly > {
  static const char* value()
  {
    return "1405c334a431797812c1007b03f031ec";
  }

  static const char* value(const ::scheduling_msgs::QueryPathOnly&) { return value(); }
};

template<>
struct DataType< ::scheduling_msgs::QueryPathOnly > {
  static const char* value()
  {
    return "scheduling_msgs/QueryPathOnly";
  }

  static const char* value(const ::scheduling_msgs::QueryPathOnly&) { return value(); }
};


// service_traits::MD5Sum< ::scheduling_msgs::QueryPathOnlyRequest> should match 
// service_traits::MD5Sum< ::scheduling_msgs::QueryPathOnly > 
template<>
struct MD5Sum< ::scheduling_msgs::QueryPathOnlyRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scheduling_msgs::QueryPathOnly >::value();
  }
  static const char* value(const ::scheduling_msgs::QueryPathOnlyRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scheduling_msgs::QueryPathOnlyRequest> should match 
// service_traits::DataType< ::scheduling_msgs::QueryPathOnly > 
template<>
struct DataType< ::scheduling_msgs::QueryPathOnlyRequest>
{
  static const char* value()
  {
    return DataType< ::scheduling_msgs::QueryPathOnly >::value();
  }
  static const char* value(const ::scheduling_msgs::QueryPathOnlyRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scheduling_msgs::QueryPathOnlyResponse> should match 
// service_traits::MD5Sum< ::scheduling_msgs::QueryPathOnly > 
template<>
struct MD5Sum< ::scheduling_msgs::QueryPathOnlyResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scheduling_msgs::QueryPathOnly >::value();
  }
  static const char* value(const ::scheduling_msgs::QueryPathOnlyResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scheduling_msgs::QueryPathOnlyResponse> should match 
// service_traits::DataType< ::scheduling_msgs::QueryPathOnly > 
template<>
struct DataType< ::scheduling_msgs::QueryPathOnlyResponse>
{
  static const char* value()
  {
    return DataType< ::scheduling_msgs::QueryPathOnly >::value();
  }
  static const char* value(const ::scheduling_msgs::QueryPathOnlyResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCHEDULING_MSGS_MESSAGE_QUERYPATHONLY_H
