// Generated by gencpp from file scheduling_msgs/ReportNavigationControlStatusResponse.msg
// DO NOT EDIT!


#ifndef SCHEDULING_MSGS_MESSAGE_REPORTNAVIGATIONCONTROLSTATUSRESPONSE_H
#define SCHEDULING_MSGS_MESSAGE_REPORTNAVIGATIONCONTROLSTATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace scheduling_msgs
{
template <class ContainerAllocator>
struct ReportNavigationControlStatusResponse_
{
  typedef ReportNavigationControlStatusResponse_<ContainerAllocator> Type;

  ReportNavigationControlStatusResponse_()
    : received(false)  {
    }
  ReportNavigationControlStatusResponse_(const ContainerAllocator& _alloc)
    : received(false)  {
  (void)_alloc;
    }



   typedef uint8_t _received_type;
  _received_type received;




  typedef boost::shared_ptr< ::scheduling_msgs::ReportNavigationControlStatusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scheduling_msgs::ReportNavigationControlStatusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct ReportNavigationControlStatusResponse_

typedef ::scheduling_msgs::ReportNavigationControlStatusResponse_<std::allocator<void> > ReportNavigationControlStatusResponse;

typedef boost::shared_ptr< ::scheduling_msgs::ReportNavigationControlStatusResponse > ReportNavigationControlStatusResponsePtr;
typedef boost::shared_ptr< ::scheduling_msgs::ReportNavigationControlStatusResponse const> ReportNavigationControlStatusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scheduling_msgs::ReportNavigationControlStatusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scheduling_msgs::ReportNavigationControlStatusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace scheduling_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'scheduling_msgs': ['/home/ouiyeah/catkin_ws/src/hitrobot/scheduling_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::scheduling_msgs::ReportNavigationControlStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scheduling_msgs::ReportNavigationControlStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scheduling_msgs::ReportNavigationControlStatusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scheduling_msgs::ReportNavigationControlStatusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scheduling_msgs::ReportNavigationControlStatusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scheduling_msgs::ReportNavigationControlStatusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scheduling_msgs::ReportNavigationControlStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dd4152e077925db952c78baadb1e48b7";
  }

  static const char* value(const ::scheduling_msgs::ReportNavigationControlStatusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdd4152e077925db9ULL;
  static const uint64_t static_value2 = 0x52c78baadb1e48b7ULL;
};

template<class ContainerAllocator>
struct DataType< ::scheduling_msgs::ReportNavigationControlStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scheduling_msgs/ReportNavigationControlStatusResponse";
  }

  static const char* value(const ::scheduling_msgs::ReportNavigationControlStatusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scheduling_msgs::ReportNavigationControlStatusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool received\n\
\n\
\n\
";
  }

  static const char* value(const ::scheduling_msgs::ReportNavigationControlStatusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scheduling_msgs::ReportNavigationControlStatusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.received);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReportNavigationControlStatusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scheduling_msgs::ReportNavigationControlStatusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scheduling_msgs::ReportNavigationControlStatusResponse_<ContainerAllocator>& v)
  {
    s << indent << "received: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.received);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCHEDULING_MSGS_MESSAGE_REPORTNAVIGATIONCONTROLSTATUSRESPONSE_H
