// Generated by gencpp from file scheduling_msgs/ReportNavigationControlStatus.msg
// DO NOT EDIT!


#ifndef SCHEDULING_MSGS_MESSAGE_REPORTNAVIGATIONCONTROLSTATUS_H
#define SCHEDULING_MSGS_MESSAGE_REPORTNAVIGATIONCONTROLSTATUS_H

#include <ros/service_traits.h>


#include <scheduling_msgs/ReportNavigationControlStatusRequest.h>
#include <scheduling_msgs/ReportNavigationControlStatusResponse.h>


namespace scheduling_msgs
{

struct ReportNavigationControlStatus
{

typedef ReportNavigationControlStatusRequest Request;
typedef ReportNavigationControlStatusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ReportNavigationControlStatus
} // namespace scheduling_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scheduling_msgs::ReportNavigationControlStatus > {
  static const char* value()
  {
    return "36e9fda8440e71d1bf5663b853455b22";
  }

  static const char* value(const ::scheduling_msgs::ReportNavigationControlStatus&) { return value(); }
};

template<>
struct DataType< ::scheduling_msgs::ReportNavigationControlStatus > {
  static const char* value()
  {
    return "scheduling_msgs/ReportNavigationControlStatus";
  }

  static const char* value(const ::scheduling_msgs::ReportNavigationControlStatus&) { return value(); }
};


// service_traits::MD5Sum< ::scheduling_msgs::ReportNavigationControlStatusRequest> should match 
// service_traits::MD5Sum< ::scheduling_msgs::ReportNavigationControlStatus > 
template<>
struct MD5Sum< ::scheduling_msgs::ReportNavigationControlStatusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scheduling_msgs::ReportNavigationControlStatus >::value();
  }
  static const char* value(const ::scheduling_msgs::ReportNavigationControlStatusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scheduling_msgs::ReportNavigationControlStatusRequest> should match 
// service_traits::DataType< ::scheduling_msgs::ReportNavigationControlStatus > 
template<>
struct DataType< ::scheduling_msgs::ReportNavigationControlStatusRequest>
{
  static const char* value()
  {
    return DataType< ::scheduling_msgs::ReportNavigationControlStatus >::value();
  }
  static const char* value(const ::scheduling_msgs::ReportNavigationControlStatusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scheduling_msgs::ReportNavigationControlStatusResponse> should match 
// service_traits::MD5Sum< ::scheduling_msgs::ReportNavigationControlStatus > 
template<>
struct MD5Sum< ::scheduling_msgs::ReportNavigationControlStatusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scheduling_msgs::ReportNavigationControlStatus >::value();
  }
  static const char* value(const ::scheduling_msgs::ReportNavigationControlStatusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scheduling_msgs::ReportNavigationControlStatusResponse> should match 
// service_traits::DataType< ::scheduling_msgs::ReportNavigationControlStatus > 
template<>
struct DataType< ::scheduling_msgs::ReportNavigationControlStatusResponse>
{
  static const char* value()
  {
    return DataType< ::scheduling_msgs::ReportNavigationControlStatus >::value();
  }
  static const char* value(const ::scheduling_msgs::ReportNavigationControlStatusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCHEDULING_MSGS_MESSAGE_REPORTNAVIGATIONCONTROLSTATUS_H
