// Generated by gencpp from file scheduling_msgs/SelectProductionMaterialResponse.msg
// DO NOT EDIT!


#ifndef SCHEDULING_MSGS_MESSAGE_SELECTPRODUCTIONMATERIALRESPONSE_H
#define SCHEDULING_MSGS_MESSAGE_SELECTPRODUCTIONMATERIALRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <scheduling_msgs/ProductionMaterialList.h>

namespace scheduling_msgs
{
template <class ContainerAllocator>
struct SelectProductionMaterialResponse_
{
  typedef SelectProductionMaterialResponse_<ContainerAllocator> Type;

  SelectProductionMaterialResponse_()
    : feedback(0)
    , message()
    , materials()  {
    }
  SelectProductionMaterialResponse_(const ContainerAllocator& _alloc)
    : feedback(0)
    , message(_alloc)
    , materials(_alloc)  {
  (void)_alloc;
    }



   typedef int32_t _feedback_type;
  _feedback_type feedback;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;

   typedef  ::scheduling_msgs::ProductionMaterialList_<ContainerAllocator>  _materials_type;
  _materials_type materials;




  typedef boost::shared_ptr< ::scheduling_msgs::SelectProductionMaterialResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scheduling_msgs::SelectProductionMaterialResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SelectProductionMaterialResponse_

typedef ::scheduling_msgs::SelectProductionMaterialResponse_<std::allocator<void> > SelectProductionMaterialResponse;

typedef boost::shared_ptr< ::scheduling_msgs::SelectProductionMaterialResponse > SelectProductionMaterialResponsePtr;
typedef boost::shared_ptr< ::scheduling_msgs::SelectProductionMaterialResponse const> SelectProductionMaterialResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scheduling_msgs::SelectProductionMaterialResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scheduling_msgs::SelectProductionMaterialResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace scheduling_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'scheduling_msgs': ['/home/ouiyeah/catkin_ws/src/scheduling_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'nav_msgs': ['/opt/ros/indigo/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::scheduling_msgs::SelectProductionMaterialResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scheduling_msgs::SelectProductionMaterialResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scheduling_msgs::SelectProductionMaterialResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scheduling_msgs::SelectProductionMaterialResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scheduling_msgs::SelectProductionMaterialResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scheduling_msgs::SelectProductionMaterialResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scheduling_msgs::SelectProductionMaterialResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "067f08d0484f8ca7c5a8110661034c0e";
  }

  static const char* value(const ::scheduling_msgs::SelectProductionMaterialResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x067f08d0484f8ca7ULL;
  static const uint64_t static_value2 = 0xc5a8110661034c0eULL;
};

template<class ContainerAllocator>
struct DataType< ::scheduling_msgs::SelectProductionMaterialResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scheduling_msgs/SelectProductionMaterialResponse";
  }

  static const char* value(const ::scheduling_msgs::SelectProductionMaterialResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scheduling_msgs::SelectProductionMaterialResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 feedback\n\
\n\
\n\
\n\
string message\n\
ProductionMaterialList materials\n\
\n\
================================================================================\n\
MSG: scheduling_msgs/ProductionMaterialList\n\
# msg for innolux\n\
ProductionMaterial[] materials\n\
================================================================================\n\
MSG: scheduling_msgs/ProductionMaterial\n\
# msg for innolux\n\
string line\n\
string station\n\
string machine\n\
string model\n\
string material_type\n\
string material_no\n\
";
  }

  static const char* value(const ::scheduling_msgs::SelectProductionMaterialResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scheduling_msgs::SelectProductionMaterialResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.feedback);
      stream.next(m.message);
      stream.next(m.materials);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SelectProductionMaterialResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scheduling_msgs::SelectProductionMaterialResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scheduling_msgs::SelectProductionMaterialResponse_<ContainerAllocator>& v)
  {
    s << indent << "feedback: ";
    Printer<int32_t>::stream(s, indent + "  ", v.feedback);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
    s << indent << "materials: ";
    s << std::endl;
    Printer< ::scheduling_msgs::ProductionMaterialList_<ContainerAllocator> >::stream(s, indent + "  ", v.materials);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCHEDULING_MSGS_MESSAGE_SELECTPRODUCTIONMATERIALRESPONSE_H
