// Generated by gencpp from file scheduling_msgs/TaskQueryAndGainPathResponse.msg
// DO NOT EDIT!


#ifndef SCHEDULING_MSGS_MESSAGE_TASKQUERYANDGAINPATHRESPONSE_H
#define SCHEDULING_MSGS_MESSAGE_TASKQUERYANDGAINPATHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace scheduling_msgs
{
template <class ContainerAllocator>
struct TaskQueryAndGainPathResponse_
{
  typedef TaskQueryAndGainPathResponse_<ContainerAllocator> Type;

  TaskQueryAndGainPathResponse_()
    : isValid(false)
    , path()  {
    }
  TaskQueryAndGainPathResponse_(const ContainerAllocator& _alloc)
    : isValid(false)
    , path(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _isValid_type;
  _isValid_type isValid;

   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose2D_<ContainerAllocator> >::other >  _path_type;
  _path_type path;




  typedef boost::shared_ptr< ::scheduling_msgs::TaskQueryAndGainPathResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::scheduling_msgs::TaskQueryAndGainPathResponse_<ContainerAllocator> const> ConstPtr;

}; // struct TaskQueryAndGainPathResponse_

typedef ::scheduling_msgs::TaskQueryAndGainPathResponse_<std::allocator<void> > TaskQueryAndGainPathResponse;

typedef boost::shared_ptr< ::scheduling_msgs::TaskQueryAndGainPathResponse > TaskQueryAndGainPathResponsePtr;
typedef boost::shared_ptr< ::scheduling_msgs::TaskQueryAndGainPathResponse const> TaskQueryAndGainPathResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::scheduling_msgs::TaskQueryAndGainPathResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::scheduling_msgs::TaskQueryAndGainPathResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace scheduling_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'scheduling_msgs': ['/home/ouiyeah/catkin_ws/src/scheduling_msgs/msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::scheduling_msgs::TaskQueryAndGainPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::scheduling_msgs::TaskQueryAndGainPathResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scheduling_msgs::TaskQueryAndGainPathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::scheduling_msgs::TaskQueryAndGainPathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scheduling_msgs::TaskQueryAndGainPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::scheduling_msgs::TaskQueryAndGainPathResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::scheduling_msgs::TaskQueryAndGainPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "feaac5dc93963716c141bd4b89eb4e7e";
  }

  static const char* value(const ::scheduling_msgs::TaskQueryAndGainPathResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfeaac5dc93963716ULL;
  static const uint64_t static_value2 = 0xc141bd4b89eb4e7eULL;
};

template<class ContainerAllocator>
struct DataType< ::scheduling_msgs::TaskQueryAndGainPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "scheduling_msgs/TaskQueryAndGainPathResponse";
  }

  static const char* value(const ::scheduling_msgs::TaskQueryAndGainPathResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::scheduling_msgs::TaskQueryAndGainPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool isValid\n\
geometry_msgs/Pose2D[] path\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::scheduling_msgs::TaskQueryAndGainPathResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::scheduling_msgs::TaskQueryAndGainPathResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.isValid);
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TaskQueryAndGainPathResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::scheduling_msgs::TaskQueryAndGainPathResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::scheduling_msgs::TaskQueryAndGainPathResponse_<ContainerAllocator>& v)
  {
    s << indent << "isValid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.isValid);
    s << indent << "path[]" << std::endl;
    for (size_t i = 0; i < v.path.size(); ++i)
    {
      s << indent << "  path[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.path[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // SCHEDULING_MSGS_MESSAGE_TASKQUERYANDGAINPATHRESPONSE_H
