// Generated by gencpp from file scheduling_msgs/TaskQueryAndGainPath.msg
// DO NOT EDIT!


#ifndef SCHEDULING_MSGS_MESSAGE_TASKQUERYANDGAINPATH_H
#define SCHEDULING_MSGS_MESSAGE_TASKQUERYANDGAINPATH_H

#include <ros/service_traits.h>


#include <scheduling_msgs/TaskQueryAndGainPathRequest.h>
#include <scheduling_msgs/TaskQueryAndGainPathResponse.h>


namespace scheduling_msgs
{

struct TaskQueryAndGainPath
{

typedef TaskQueryAndGainPathRequest Request;
typedef TaskQueryAndGainPathResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct TaskQueryAndGainPath
} // namespace scheduling_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::scheduling_msgs::TaskQueryAndGainPath > {
  static const char* value()
  {
    return "2558b785b45a88b34b4d9ecdb1d64193";
  }

  static const char* value(const ::scheduling_msgs::TaskQueryAndGainPath&) { return value(); }
};

template<>
struct DataType< ::scheduling_msgs::TaskQueryAndGainPath > {
  static const char* value()
  {
    return "scheduling_msgs/TaskQueryAndGainPath";
  }

  static const char* value(const ::scheduling_msgs::TaskQueryAndGainPath&) { return value(); }
};


// service_traits::MD5Sum< ::scheduling_msgs::TaskQueryAndGainPathRequest> should match 
// service_traits::MD5Sum< ::scheduling_msgs::TaskQueryAndGainPath > 
template<>
struct MD5Sum< ::scheduling_msgs::TaskQueryAndGainPathRequest>
{
  static const char* value()
  {
    return MD5Sum< ::scheduling_msgs::TaskQueryAndGainPath >::value();
  }
  static const char* value(const ::scheduling_msgs::TaskQueryAndGainPathRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::scheduling_msgs::TaskQueryAndGainPathRequest> should match 
// service_traits::DataType< ::scheduling_msgs::TaskQueryAndGainPath > 
template<>
struct DataType< ::scheduling_msgs::TaskQueryAndGainPathRequest>
{
  static const char* value()
  {
    return DataType< ::scheduling_msgs::TaskQueryAndGainPath >::value();
  }
  static const char* value(const ::scheduling_msgs::TaskQueryAndGainPathRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::scheduling_msgs::TaskQueryAndGainPathResponse> should match 
// service_traits::MD5Sum< ::scheduling_msgs::TaskQueryAndGainPath > 
template<>
struct MD5Sum< ::scheduling_msgs::TaskQueryAndGainPathResponse>
{
  static const char* value()
  {
    return MD5Sum< ::scheduling_msgs::TaskQueryAndGainPath >::value();
  }
  static const char* value(const ::scheduling_msgs::TaskQueryAndGainPathResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::scheduling_msgs::TaskQueryAndGainPathResponse> should match 
// service_traits::DataType< ::scheduling_msgs::TaskQueryAndGainPath > 
template<>
struct DataType< ::scheduling_msgs::TaskQueryAndGainPathResponse>
{
  static const char* value()
  {
    return DataType< ::scheduling_msgs::TaskQueryAndGainPath >::value();
  }
  static const char* value(const ::scheduling_msgs::TaskQueryAndGainPathResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SCHEDULING_MSGS_MESSAGE_TASKQUERYANDGAINPATH_H
