(cl:defpackage cob_mimic-msg
  (:use )
  (:export
   "<SETMIMICGOAL>"
   "SETMIMICGOAL"
   "<SETMIMICACTIONGOAL>"
   "SETMIMICACTIONGOAL"
   "<SETMIMICACTIONRESULT>"
   "SETMIMICACTIONRESULT"
   "<SETMIMICACTION>"
   "SETMIMICACTION"
   "<SETMIMICRESULT>"
   "SETMIMICRESULT"
   "<SETMIMICACTIONFEEDBACK>"
   "SETMIMICACTIONFEEDBACK"
   "<SETMIMICFEEDBACK>"
   "SETMIMICFEEDBACK"
  ))

