; Auto-generated. Do not edit!


(cl:in-package cob_sound-msg)


;//! \htmlinclude PlayFeedback.msg.html

(cl:defclass <PlayFeedback> (roslisp-msg-protocol:ros-message)
  ((position
    :reader position
    :initarg :position
    :type cl:float
    :initform 0.0)
   (time
    :reader time
    :initarg :time
    :type cl:integer
    :initform 0))
)

(cl:defclass PlayFeedback (<PlayFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <PlayFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'PlayFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name cob_sound-msg:<PlayFeedback> is deprecated: use cob_sound-msg:PlayFeedback instead.")))

(cl:ensure-generic-function 'position-val :lambda-list '(m))
(cl:defmethod position-val ((m <PlayFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_sound-msg:position-val is deprecated.  Use cob_sound-msg:position instead.")
  (position m))

(cl:ensure-generic-function 'time-val :lambda-list '(m))
(cl:defmethod time-val ((m <PlayFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader cob_sound-msg:time-val is deprecated.  Use cob_sound-msg:time instead.")
  (time m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <PlayFeedback>) ostream)
  "Serializes a message object of type '<PlayFeedback>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'position))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let* ((signed (cl:slot-value msg 'time)) (unsigned (cl:if (cl:< signed 0) (cl:+ signed 18446744073709551616) signed)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) unsigned) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) unsigned) ostream)
    )
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <PlayFeedback>) istream)
  "Deserializes a message object of type '<PlayFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'position) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((unsigned 0))
      (cl:setf (cl:ldb (cl:byte 8 0) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) unsigned) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) unsigned) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'time) (cl:if (cl:< unsigned 9223372036854775808) unsigned (cl:- unsigned 18446744073709551616))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<PlayFeedback>)))
  "Returns string type for a message object of type '<PlayFeedback>"
  "cob_sound/PlayFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'PlayFeedback)))
  "Returns string type for a message object of type 'PlayFeedback"
  "cob_sound/PlayFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<PlayFeedback>)))
  "Returns md5sum for a message object of type '<PlayFeedback>"
  "f06b964fe8afc9fc6f0973a48e95fd13")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'PlayFeedback)))
  "Returns md5sum for a message object of type 'PlayFeedback"
  "f06b964fe8afc9fc6f0973a48e95fd13")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<PlayFeedback>)))
  "Returns full string definition for message of type '<PlayFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 position    #the current position in the media file as percentage between 0.0 and 1.0~%int64 time        #the current time in the media file (in ms)~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'PlayFeedback)))
  "Returns full string definition for message of type 'PlayFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%float32 position    #the current position in the media file as percentage between 0.0 and 1.0~%int64 time        #the current time in the media file (in ms)~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <PlayFeedback>))
  (cl:+ 0
     4
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <PlayFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'PlayFeedback
    (cl:cons ':position (position msg))
    (cl:cons ':time (time msg))
))
