# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from cob_cartesian_controller/Profile.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Profile(genpy.Message):
  _md5sum = "3631ecf157bdfedf0f8cb3d5f838c11b"
  _type = "cob_cartesian_controller/Profile"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 RAMP=1
uint8 SINOID=2
uint8 profile_type

float64 vel
float64 accl
"""
  # Pseudo-constants
  RAMP = 1
  SINOID = 2

  __slots__ = ['profile_type','vel','accl']
  _slot_types = ['uint8','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       profile_type,vel,accl

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Profile, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.profile_type is None:
        self.profile_type = 0
      if self.vel is None:
        self.vel = 0.
      if self.accl is None:
        self.accl = 0.
    else:
      self.profile_type = 0
      self.vel = 0.
      self.accl = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_B2d.pack(_x.profile_type, _x.vel, _x.accl))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.profile_type, _x.vel, _x.accl,) = _struct_B2d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_B2d.pack(_x.profile_type, _x.vel, _x.accl))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 17
      (_x.profile_type, _x.vel, _x.accl,) = _struct_B2d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_B2d = struct.Struct("<B2d")
